### PR TITLE
sonarqube integration

### PR DESCRIPTION
**Pull request by dzlab**
This is an attempt to enable the use of SonarQube.com for quality analysis.
To set the values for the needed environment variables in Travis follow this [documentation](https://docs.travis-ci.com/user/sonarqube/#SonarQube-Scanner-for-Maven):
- `SONAR_ORGANIZATION`: name of the organisation in Sonarqube
- `SONAR_TOKEN`: the token generated in Sonarqube
- `GITHUB_TOKEN`: (to be able to run sonar on pull requests) github personal access token [doc](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)

### CODE REVIEW

**Comment by freastro** [comment]
@dzlab The build says that the SonarQube analysis was skipped. Any ideas? I tried using the GitHub SonarScanner plugin from the command-line and that seems to be working.

**Comment by dzlab** [comment]
@freastro it may be a build for non master branch, is it? you can force the analysis to run for some specific branches by explicitly declaring them in `.travis.yml` (see [documentation](https://docs.travis-ci.com/user/sonarqube/#Activation-for-branches)).

**Comment by freastro** [comment]
@dzlab Actually, I meant the build for this pull request. You can see it below where it says "All checks have passed". I'd like to see it working for this pull request before merging in the changes. I'm thinking something like this should work:
```
if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ -n "${GITHUB_TOKEN:-}" ]; then
    mvn clean install sonar:sonar -B -V \
        -Dsonar.exclusions=**/SparkInterpreterBuilder211.java \
        -Dsonar.analysis.mode=preview \
        -Dsonar.github.pullRequest=${TRAVIS_PULL_REQUEST} \
        -Dsonar.github.repository=${TRAVIS_REPO_SLUG} \
        -Dsonar.github.oauth=${GITHUB_TOKEN} \
        -Dsonar.host.url=https://sonarqube.com/
else
    mvn clean install -B -V
fi
```

**Comment by dzlab** [comment]
@freastro no need to configure the maven plugin as it will be done by the travis add-on (see [link](http://stackoverflow.com/questions/43184018/failed-to-execute-goal-org-sonarsource-scanner-mavensonar-maven-plugin3-3-0-60))

**Comment by freastro** [comment]
@dzlab The Maven plugin needs to be configured because the Travis add-on isn't working. Please see the build log:
https://travis-ci.org/Teradata/kylo/builds/221808525
> Skipping SonarQube Scan because it is not running in a secure environment

**Comment by dzlab** [comment]
I don't know, but in the logs I also see

> $ export SONARQUBE_SKIPPED=true

Are you sure sonar addon is properly configure because I don't see any export for the `$SONAR_TOKEN`.

**Comment by freastro** [comment]
I got this working and committed it separately.

**Pull request closed without merging**
