### PR TITLE
Release/0.8.3使用querydatabasestable抓取1亿条数据，每次抓20万条，flowfile也是20万。该feed就会产生很多的job，但是job的数目明显不对。

### PR DESCRIPTION
**Pull request by lsasta**
在nifi开始运行的时候，基本没啥问题，同时会有一系列的job同时出现在jobs里面。但是运行久了，就不产生新的job了。可是nifi这边数据还有很多没有处理！这个是什么原因？

### CODE REVIEW

**Comment by claudiu-stanciu** [comment]
@lsasta You might want to change the from branch. I don't think that you want to make a PR from teradata/kylo release branch to master :). Also it might help to have the description in english ;)

**Comment by ben-adazza** [comment]
The translated text reads more like a bug report than a PR. Maybe try to articulate the problem in the google group instead of as a PR? 

>In the nifi start running, the basic lack of problems, while there will be a series of jobs at the same time in the jobs inside. But the operation for a long time, it does not produce a new job. But there are a lot of data here nifi no deal! What is the reason for this?

**Comment by lsasta** [comment]
sorry!!!
i am not good at english. so,i wirte chinese.
but,i have found the answer of this issue..
my question like this:
https://groups.google.com/forum/#!topic/kylo-community/LTMF9nJAV6A

forgive me !!

**Comment by ben-adazza** [comment]
No problem. It is good you found a solution in the google group.

**Comment by freastro** [comment]
Issue is resolved. Closing...

**Pull request closed without merging**
