### PR TITLE
Autodetect kerberos settings based on spark.properties for spark-submit shell

### PR DESCRIPTION
**Pull request by claudiu-stanciu**

### CODE REVIEW

**Comment by claudiu-stanciu** [comment]
Based on http://kylo.readthedocs.io/en/latest/installation/KyloConfigurationforaKerberosCluster.html#configuration-steps

**Comment by jeremymerrifield** [comment]
I am not sure we should be duplicating properties in the bin script. What if someone changes the property in the spark.properties file? I talked to Greg and it sounds like there might be a bug where the kerberos properties aren't being loaded from the spark.properties correct (in local mode). If that is the case we need to fix the code.

**Comment by claudiu-stanciu** [comment]
@jeremymerrifield I added that code as spark wasn't getting authenticated vs kerberos, without passing explicitly the principal and keytab for the spark-submit, even with the kerberos properties defined in spark.properties. Spark was running in local mode.

**Comment by freastro** [comment]
@claudiu-stanciu This can be done in Java code that parses the spark.properties file instead of trying to parse the file in bash. It used to work that way until a recent change so we'd prefer to revert that change rather than implementing it in bash.

**Comment by claudiu-stanciu** [comment]
@freastro @jeremymerrifield I would prefer it as well that it was the java code which parsed the spark.properties, than a dirty bash script :D.
I'll close the PR then. 
Thanks for the review

**Pull request closed without merging**
