### PR TITLE
KYLO-322 Add FindBugs static code analysis tool to the build configuration

### PR DESCRIPTION
**Pull request by peter-gergely-horvath**
FindBugs is a _very_ powerful static code analysis tool, which examines Java bytecode and detects a wide range of issues. 

This change adds FindBugs to Kylo build configuration so that FindBugs analysis is performed and a HTML report is generated.

### CODE REVIEW

**Comment by freastro** [comment]
Could you submit KYLO-322 as a separate pull request? Thanks!

**Comment by peter-gergely-horvath** [comment]
Hi, sorry, a bit of Git confusion on my end. It's been corrected so that the pull request now contains the intended commit only.

**Comment by freastro** [comment]
I've been thinking about this and I think a good first use case is for pull requests. I think we should stick with SonarQube though since that's what we're using for development. Peter, do want to look into integrating the [SonarSource GitHub plugin](https://docs.sonarqube.org/display/PLUG/GitHub+Plugin) into our Travis CI build? An example is at the bottom of the linked page and we can use the public sonarqube.com for analysis.

**Comment by peter-gergely-horvath** [comment]
@freastro, once I have some time, I'm happy to look into that. :) I think SonarSource is a great tool ... 
**...BUT:** I still do think it is worth having this FindBugs configuration in place. Your build actually failing in front of your eyes after your latest changes in the workspace (**hopefully** on your local development machine, **before** committing/pushing it to the repo) is a much more powerful incentive to fix the code, than any tool generating reports somewhere maybe hours later might be. 

Failing the build from FindBugs means poor quality code does NOT even REACH the repository. 

Please note this change would only be the first step by generating reports one can review, but would NOT fail the build. (So it would not be a painful, long process to fix current issues first) and
**I am more than happy to assist you ironing out any issues FindBugs detects by submitting small, targeted Git pull requests to address them.**

**Comment by dzlab** [comment]
@freastro I submitted a pull request to integrate SonarQube in Travis builds #16

**Comment by peter-gergely-horvath** [comment]
OK, that's brilliant, it should help catching issues early. :)

**Pull request closed without merging**
