### PR TITLE
sonarqube integration

### PR DESCRIPTION
**Pull request by dzlab**
This is an attempt to enable the use of SonarQube.com for quality analysis.
To set the values for the needed environment variables in Travis follow this [documentation](https://docs.travis-ci.com/user/sonarqube/#SonarQube-Scanner-for-Maven):
- `SONAR_ORGANIZATION`: name of the organisation in Sonarqube
- `SONAR_TOKEN`: the token generated in Sonarqube
- `GITHUB_TOKEN`: (to be able to run sonar on pull requests) github personal access token [doc](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)

### CODE REVIEW

**Comment by freastro** [comment]
@dzlab Thanks for this, but we've already configured a Jenkins build to do this internally. The only thing we're missing is the GitHub plugin for SonarQube. If you'd like to update your pull request with this instead, the documentation is here: https://docs.sonarqube.org/display/PLUG/GitHub+Plugin

**Comment by dzlab** [comment]
@freastro I thought you were using Travis (as you did mention it in the findbugs discussion). I'll update my pull request but you need to have a dedicated github user (e.g. KyloTech) like sonarqube they are using [SonarTech](https://github.com/SonarTech) to analyse pull requests.

**Comment by freastro** [comment]
I took another look at how SonarQube is using this and it looks like it cannot be used for untrusted code such as a pull request from a fork. Same for the Travis addon in your pull request. Let's revisit is this when support for external pull requests is added.

**Comment by dzlab** [comment]
I posted a question on [sonarqube user group](https://groups.google.com/forum/#!topic/sonarqube/8U61ir6N6U0) to confirm if it's not possible to analyse pull requests from a fork.

**Comment by dzlab** [comment]
@freastro https://groups.google.com/forum/#!topic/sonarqube/8U61ir6N6U0

> Running automatically the build + tests + scanner on an untrusted P/R could be a security issue

**Comment by freastro** [comment]
Let's try it anyways. Please use the GitHub plugin with this token for pull requests: fdb211764ad34b04d4cc2457bf00b72a48f7762c

**Comment by freastro** [comment]
I got an email from GitHub saying the token was revoked because it was publicly available. Looks like this is not going to work.

**Comment by dzlab** [comment]
@freastro we can use env variables as I previously suggested, just set `$GITHUB_TOKEN`on the project settings in the Travis dashboard. This way the tokens won't be publically available.
screen shot 2017-04-13 at 10 38 39

**Comment by freastro** [comment]
@dzlab You're right. By default they're not available to forks but it looks like there's an option to allow it. We'll still need to use the Sonar maven plugin with the GitHub plugin though since Travis won't run the SonarQube analysis for pull requests.

**Comment by dzlab** [comment]
@freastro I think I screwed this pull request after a rebase (I see 1000 file changes). I better close it and recreate a new one, no?

**Comment by freastro** [comment]
@dzlab That would be good. Thanks!

**Pull request closed without merging**
